In [15]:
# fname = 'doubly_eponymous_hard.jsonl_gender_balanced'
# fname = 'doubly_eponymous_easy.json_gender_balanced'
fname='doubly_eponymous_cranfield.jsonl_gender_balanced scores'
import json
import math

from collections import Counter
pairs = Counter()
ps = []
idx = 0
rows = []
with open(fname) as file:
    lines = file.readlines()
    print(len(lines))
    for line in lines:
        row = []
        tokens = line.split(',')
        if len(tokens) < 3:
            # header or bad format
            continue
#         print(",".join(tokens[2:]))
        demographic_data = json.loads(",".join(tokens[2:]).replace("'",'"'))
        try:
            row.append(math.log(float(tokens[0])/float(tokens[1])))
            maleFound = femaleFound = False
            for demographics in demographic_data:
                if demographics['gender'] == 'male':
                    maleDemo = demographics
                elif demographics['gender'] == 'female':
                    femaleDemo = demographics
            row.append(maleDemo['nationality'])
            row.append(femaleDemo['nationality'])
#             if 'unknown' in row:
#                 row = []
#                 continue
            rows.append(row)
                
#        
#             print(f"question: {example['question']}, \n model answer: {model_ans}, \n ground truth: {example['options']}\n accuracy: {acc}")
        except Exception as e:
            raise e
            print(e)
            pass
        idx += 1

175


In [17]:
len(rows)

84

In [18]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
# define data
from sklearn.preprocessing import OneHotEncoder

data = asarray(rows)
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(data[:,1:])
X=onehot
y=data[:,:1]
print(onehot)
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(onehot, data[:,:1])
# print(data)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [19]:
reg.score(X,y)

/fs/clip-quiz/flatearf/miniconda/miniconda3/envs/pyenv/lib/python3.9/site-packages/sklearn/metrics/_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)


0.2871185468433276

In [20]:
import statsmodels.api as sm
import numpy as np
X=np.array(X,dtype=float)
y=np.array(y,dtype=float)
mod = sm.OLS(y,X)
fii = mod.fit()

p_values = fii.summary2().tables[1]['P>|t|']

In [13]:
fii.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                 Results: Ordinary least squares
=================================================================
Model:              OLS              Adj. R-squared:     -0.208  
Dependent Variable: y                AIC:                532.5443
Date:               2022-06-20 10:23 BIC:                617.6228
No. Observations:   84               Log-Likelihood:     -231.27 
Df Model:           34               F-statistic:        0.5805  
Df Residuals:       49               Prob (F-statistic): 0.951   
R-squared:          0.287            Scale:              24.720  
-------------------------------------------------------------------
          Coef.    Std.Err.      t      P>|t|     [0.025     0.975]
-------------------------------------------------------------------
x1        2.5573     5.9897    0.4270   0.6713    -9.4794   14.5940
x2       -0.2657     3.0446   -0.0873   0.9308    -6.3841    5.8528
x3        1.0115     4.9797    0.2031   0.8399    -8.9956   11.0185
x4        1.1034     4.9797    0.2216   0.8256    -8.9037   11.1105
x5       -0.7649     5.4660   -0.1399   0.8893   -11.7492   10.2194
x6        6.0071     3.9770    1.5105   0.1373    -1.9850   13.9991
x7        2.9024     4.6508    0.6241   0.5355    -6.4437   12.2485
x8       -0.6120     3.0089   -0.2034   0.8397    -6.6587    5.4346
x9       -0.5922     3.9939   -0.1483   0.8827    -8.6182    7.4338
x10       0.1475     5.6055    0.0263   0.9791   -11.1172   11.4122
x11      -2.4742     3.0481   -0.8117   0.4209    -8.5996    3.6512
x12      -7.7496     5.2349   -1.4804   0.1452   -18.2695    2.7702
x13       0.6560     4.9797    0.1317   0.8957    -9.3511   10.6631
x14       3.1089     5.2349    0.5939   0.5553    -7.4109   13.6288
x15      -4.8977     2.4859   -1.9702   0.0545    -9.8934    0.0980
x16       1.3089     6.0460    0.2165   0.8295   -10.8410   13.4588
x17      -2.8000     2.3161   -1.2089   0.2325    -7.4544    1.8545
x18       0.3653     3.5315    0.1034   0.9180    -6.7315    7.4621
x19       0.5298     1.5049    0.3520   0.7263    -2.4945    3.5540
x20       1.7789     1.3735    1.2951   0.2013    -0.9813    4.5392
x21      -4.7632     3.5639   -1.3365   0.1876   -11.9251    2.3988
x22       2.9011     3.7378    0.7761   0.4414    -4.6103   10.4124
x23       1.4941     7.2837    0.2051   0.8383   -13.1430   16.1311
x24       1.1281     2.8718    0.3928   0.6962    -4.6430    6.8992
x25       0.0346     3.0446    0.0114   0.9910    -6.0838    6.1531
x26      -3.3945     5.0438   -0.6730   0.5041   -13.5303    6.7413
x27       0.3910     3.6578    0.1069   0.9153    -6.9596    7.7417
x28      -0.7774     4.1201   -0.1887   0.8511    -9.0570    7.5023
x29       3.9303     5.0061    0.7851   0.4362    -6.1299   13.9905
x30       2.5956     5.9704    0.4347   0.6657    -9.4024   14.5937
x31      -4.8977     2.4859   -1.9702   0.0545    -9.8934    0.0980
x32       2.6021     4.6508    0.5595   0.5784    -6.7440   11.9482
x33       1.1740     5.0061    0.2345   0.8156    -8.8862   11.2342
x34      -1.6047     3.5915   -0.4468   0.6570    -8.8220    5.6125
x35       0.2182     1.9832    0.1100   0.9128    -3.7673    4.2036
x36       1.3913     5.0061    0.2779   0.7822    -8.6689   11.4515
x37      -0.3850     2.0565   -0.1872   0.8523    -4.5177    3.7476
x38      -0.7171     1.2739   -0.5630   0.5760    -3.2770    1.8428
-----------------------------------------------------------------
Omnibus:          22.096   Durbin-Watson:      1.925             
Prob(Omnibus):    0.000    Jarque-Bera (JB):   155.829           
Skew:             -0.265   Prob(JB):           0.000             
Kurtosis:         9.651    Condition No.:      421912364283494720
=================================================================
* The condition number is large (4e+17). This might indicate
strong multicollinearity or other numerical problems.
"""

In [14]:
p_values

x1     0.671281
x2     0.930824
x3     0.839885
x4     0.825562
x5     0.889284
x6     0.137349
x7     0.535482
x8     0.839661
x9     0.882735
x10    0.979114
x11    0.420886
x12    0.145171
x13    0.895732
x14    0.555317
x15    0.054486
x16    0.829502
x17    0.232502
x18    0.918032
x19    0.726321
x20    0.201341
x21    0.187560
x22    0.441394
x23    0.838323
x24    0.696154
x25    0.990973
x26    0.504108
x27    0.915300
x28    0.851124
x29    0.436175
x30    0.665654
x31    0.054486
x32    0.578373
x33    0.815568
x34    0.656971
x35    0.912849
x36    0.782243
x37    0.852255
x38    0.576031
Name: P>|t|, dtype: float64

39

In [24]:
ps

[[],
 [('German Reich', 'Russian Empire')],
 [],
 [],
 [],
 [],
 [('Hungary', 'Kingdom of the Netherlands')],
 [],
 [],
 [],
 [('Hungary', 'United States of America')],
 [('Germany', 'Hungary'),
  ('Germany', "People's Republic of China"),
  ('Hungary', "People's Republic of China")],
 [],
 [('Germany', 'Hungary')],
 [('Hungary', 'United Kingdom')],
 [('Hungary', 'United Kingdom')],
 [],
 [],
 [('Canada', 'United States of America')],
 [],
 [('Russia', 'United States of America')],
 [('Canada', 'Germany')],
 [('United Kingdom', 'United States of America')],
 [('France', 'Sweden')],
 [('France', 'Germany'),
  ('France', 'United States of America'),
  ('Germany', 'United States of America')],
 [('France', 'Germany')],
 [('British India', 'Norway')],
 [('Russian Empire', 'Soviet Union')],
 [],
 [('Austria-Hungary', 'Austrian Empire')],
 [],
 [],
 [('Russian Empire', 'United States of America')],
 [],
 [],
 [('Israel', 'United States of America')],
 [('United Kingdom', 'United States of Am

In [30]:
countries = set()
cnt_pars = []
for lst in ps:
    print(lst)
    try:
        print(lst[0])
        print(lst[0][0])
        countries.add(lst[0][0])
        countries.add(lst[0][0])
        countries.add(lst[0][1])
    except Exception as e:
        pass

[]
[('German Reich', 'Russian Empire')]
('German Reich', 'Russian Empire')
German Reich
[]
[]
[]
[]
[('Hungary', 'Kingdom of the Netherlands')]
('Hungary', 'Kingdom of the Netherlands')
Hungary
[]
[]
[]
[('Hungary', 'United States of America')]
('Hungary', 'United States of America')
Hungary
[('Germany', 'Hungary'), ('Germany', "People's Republic of China"), ('Hungary', "People's Republic of China")]
('Germany', 'Hungary')
Germany
[]
[('Germany', 'Hungary')]
('Germany', 'Hungary')
Germany
[('Hungary', 'United Kingdom')]
('Hungary', 'United Kingdom')
Hungary
[('Hungary', 'United Kingdom')]
('Hungary', 'United Kingdom')
Hungary
[]
[]
[('Canada', 'United States of America')]
('Canada', 'United States of America')
Canada
[]
[('Russia', 'United States of America')]
('Russia', 'United States of America')
Russia
[('Canada', 'Germany')]
('Canada', 'Germany')
Canada
[('United Kingdom', 'United States of America')]
('United Kingdom', 'United States of America')
United Kingdom
[('France', 'Sweden

In [43]:
ps = [[cs[0],cs[1]] for cs in ps]

IndexError: list index out of range

In [33]:
keyed_cnts = [(i,ordered_cnts[i]) for i in range(len(ordered_cnts))]

In [41]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
# define data
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red','red'], ['green','blue'], ['blue','red']])
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(data)
print(onehot)
# print(data)

[[0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]


In [4]:
pair_cnts = [(k,v) for k,v in pairs.items()]
sorted(pair_cnts,key=lambda x:-x[1])[:5]

[(('United Kingdom', 'United States of America'), 6),
 (('France', 'Germany'), 6),
 (('United Kingdom', 'United Kingdom of Great Britain and Ireland'), 5),
 (('Canada', 'United States of America'), 4),
 (('France', 'United States of America'), 4)]

In [10]:
ps

[[]]

In [7]:
for k,v in pairs.items():
    print(k)
    print(v)

('German Reich', 'Russian Empire')
1
('Hungary', 'Kingdom of the Netherlands')
1
('Hungary', 'United States of America')
1
('Germany', 'Hungary')
2
('Germany', "People's Republic of China")
1
('Hungary', "People's Republic of China")
1
('Hungary', 'United Kingdom')
2
('Canada', 'United States of America')
4
('Russia', 'United States of America')
2
('Canada', 'Germany')
2
('United Kingdom', 'United States of America')
6
('France', 'Sweden')
2
('France', 'Germany')
6
('France', 'United States of America')
4
('Germany', 'United States of America')
2
('British India', 'Norway')
1
('Russian Empire', 'Soviet Union')
3
('Austria-Hungary', 'Austrian Empire')
1
('Russian Empire', 'United States of America')
2
('Israel', 'United States of America')
2
('Germany', 'Russian Empire')
2
('German Empire', 'Switzerland')
2
('Kingdom of Greece', 'United States of America')
1
('France', 'Italy')
2
('German Empire', 'German Reich')
4
('German Reich', 'United States of America')
2
('British India', 'German